### ISSUE TITLE
Set safeties

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#316]
Pressing set safeties raises:
Traceback (most recent call last):
  File "/Users/julio/PycharmProjects/cockpit/cockpit/gui/macroStage/macroStageWindow.py", line 164, in <lambda>
    lambda event: cockpit.gui.dialogs.safetyMinDialog.showDialog(self.GetParent()))
  File "/Users/julio/PycharmProjects/cockpit/cockpit/gui/dialogs/safetyMinDialog.py", line 156, in showDialog
    dialog = SafetyMinDialog(parent)
  File "/Users/julio/PycharmProjects/cockpit/cockpit/gui/dialogs/safetyMinDialog.py", line 126, in __init__
    self.Bind(wx.EVT_BUTTON, wx.ID_OK, self.OnStart)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wx/core.py", line 1350, in _EvtHandler_Bind
    assert callable(handler) or handler is None
AssertionError

**Comment by iandobbie** [comment]
There has always been a weird bug with the stage safety’s. Never been a major problem before so I have so far ignored it.

Ian

Sent from my iPhone

On 2 Jul 2018, at 15:57, juliomateoslangerak <notifications@github.com<mailto:notifications@github.com>> wrote:


Pressing set safeties raises:
Traceback (most recent call last):
File "/Users/julio/PycharmProjects/cockpit/cockpit/gui/macroStage/macroStageWindow.py", line 164, in
lambda event: cockpit.gui.dialogs.safetyMinDialog.showDialog(self.GetParent()))
File "/Users/julio/PycharmProjects/cockpit/cockpit/gui/dialogs/safetyMinDialog.py", line 156, in showDialog
dialog = SafetyMinDialog(parent)
File "/Users/julio/PycharmProjects/cockpit/cockpit/gui/dialogs/safetyMinDialog.py", line 126, in init
self.Bind(wx.EVT_BUTTON, wx.ID_OK, self.OnStart)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wx/core.py", line 1350, in _EvtHandler_Bind
assert callable(handler) or handler is None
AssertionError

**Comment by iandobbie** [comment]
Mick's macrostage fixes seem to have fixed the safety loading issue. It all seems to work as expected on DeepSIM so I hope it also works on Julio's setup with these fixes.

**Comment by mickp** [comment]
Calling this fixed as of #357 .
