### ISSUE TITLE
attempts to resize mosaic canvas before it has been painted

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit#368]
Starting cockpit in my Linux system (Debian Buster, Gnome 3.28.2, display server Wayland but GDK_BACKEND set to x11, wxPython version 3.0.2, python 2) raises the following error:

```
Initialization failed: unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/home/carandraug/src/cockpit/cockpit/cockpit/__init__.py", line 148, in OnInit
    cockpit.gui.mosaic.window.makeWindow(frame)
  File "/home/carandraug/src/cockpit/cockpit/cockpit/gui/mosaic/window.py", line 1328, in makeWindow
    window.centerCanvas()
  File "/home/carandraug/src/cockpit/cockpit/cockpit/gui/mosaic/window.py", line 289, in centerCanvas
    curPosition[1]-self.offset[1], scale)
  File "/home/carandraug/src/cockpit/cockpit/cockpit/gui/mosaic/canvas.py", line 368, in zoomTo
    self.dx = -x * scale + self.width / 2
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

Basically the following should happen during the mosaic `makeWindow`:

1. constructs `MosaicWindow` which also constructs a `MosaicCanvas` with `width` set to `None`
2. calls `MosaicWindow.Show` which triggers show event on the window, which then triggers paint event on the window, which then triggers paint event on the canvas.
3. handling of paint event by the canvas calls `MosaicCanvas.initGL` which sets `width` based on the window size.
4. back outside the event loop, `MosaicWindow.centerCanvas` is called which calls `MosaicCanvas.zoomTo` which makes use the canvas `width`.

The problem is that `zoomTo` is outside the event loop and before the paint event is handled, so `width` is still set to None and causing the error.

I'm unsure where the bug is though. `wxWindow.Show` in wxpython and wxwidgets has a return value for the window being show, which would suggest that the show event has been handled. However, that is not happening. Checking the C++ source, it calls `HandleWindowEvent` and then just returns true and it's not clear to me if that means that the event has been handled. Print debugging certainly shows that in my system that means the event has not been handled after `Show` returns.

The canvas `width` is set by `MosaicCanvas.initGL` which is called by `MosaicCanvas.onPaint`. I'm guessing that `Show` is meant to trigger a paint event via a show event.  However, on my setup 

However, during the making of the mosaic window the paint event has not yet been processed, so `width` has not yet been set.

**Comment by carandraug** [comment]
I have asked on #wxwidgets and for them seems it is obvious that `Show` only triggers the event and that it return before the event is handled. Basically, we can't expect the canvas `initGL` to have already been called.

I have two (very related) fixes on my fork, branch `canvas-sizing`.

`a8ff11646e6b` replaces the height and width with properties that call `GetClientSize()` each time. This is the least intrusive change since the interface does not change but may mean multiple calls to `GetClientSize`.

Grepping the project seems like the canvas width and height property are not actually used anywhere else and so can be removed. So the alternative `36e8c5380e1d...3243b00df808` just calls `GetClientSize` once on each method that needs access to height and width. This fixes it on Linux and seems to not break on Windows.

Changes also remove the `setSize` method since it can be replaced with `SetClientSize`.

**Comment by carandraug** [comment]
Spoke with Mick who tested it on Windows too.  Apparently this is not a Linux issue only, it was also an intermittent issue on Windows. Pushed fix. Closing as fixed.
