### ISSUE TITLE
consecutive deletion of marked sites fails on gtk

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit#408]
To reproduce:

1. start cockpit
2. save a bunch of sites on the mosaic window (Mark site button on the mosaic window)
3. select one of the sites in the list of saved sites
4. click 'Deleted selected sites' button on the mosaic window. Twice.

The second time will raise the following error:

```
Traceback (most recent call last):
  File "/home/carandraug/src/cockpit/cockpit/gui/mosaic/window.py", line 496, in <lambda>
    button.Bind(wx.EVT_BUTTON, lambda event: leftAction())
  File "/home/carandraug/src/cockpit/cockpit/gui/mosaic/window.py", line 986, in deleteSelectedSites
    self.selectedSites.remove(cockpit.interfaces.stageMover.getSite(siteID))
KeyError: <cockpit.interfaces.stageMover.Site object at 0x7fa850057940>
```

On MSW, deleting a selected item removes the selection. On gtk3, deleting a selected item moves the selection to the next item. Because `MosaicWindow` has its own internal list of selected sites, they get out of sync after deleting sites. The second time it tries to delete the selected sites it, fails to find them on `MosaicWindow.selectedSites`.

Weirdly, `ListBox.Deselect`ing the site before `Delete` still moves the selection to the next time on gtk3 so I'm fixing this with simply Deselecting everything at the end.

However, `MosaicWindow` having its own internal list of selected sites means that there's scope to get out of scope in some others way. It should probably get the selection each time from `ListBox`.

I have reported the difference of behavior on `ListBox.Delete` upstream at https://trac.wxwidgets.org/ticket/18267

**Comment by carandraug** [comment]
This is fixed with commit f667910708ad155918d0cbdd23cdbb7b2f3cc5d0
