### ISSUE TITLE
Mainwindow background right-click menu.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#426]
The main rightclick menu doesn't work in the latest version at diamond. Is this another python2/3 error?

Traceback (most recent call last):
  File "c:\b24\cockpit\cockpit\gui\mainWindow.py", line 321, in <lambda>
    self.Bind(wx.EVT_CONTEXT_MENU, lambda event: keyboard.martialWindows(self))
  File "c:\b24\cockpit\cockpit\gui\keyboard.py", line 187, in martialWindows
    from cockpit.util import csv_plotter
  File "c:\b24\cockpit\cockpit\util\csv_plotter.py", line 292
    iml.Add(wx.Bitmap.FromRGBA(*BMP_SIZE, *self.tree.GetBackgroundColour() ))
                                     ^
SyntaxError: invalid syntax

**Comment by mickp** [comment]
Yep - that's a python 2/3 thing.
