### ISSUE TITLE
Move to site fails with objective offsets.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#487]
Traceback (most recent call last):
  File "c:\b24\cockpit\cockpit\gui\mosaic\window.py", line 966, in onDoubleClickSite
    cockpit.interfaces.stageMover.goToSite(siteID)
  File "c:\b24\cockpit\cockpit\interfaces\stageMover.py", line 338, in goToSite
    offsetPosition[i]=offsetPosition[i]+objOffset[i]
TypeError: 'tuple' object does not support item assignment
Traceback (most recent call last):
  File "c:\b24\cockpit\cockpit\gui\mosaic\window.py", line 966, in onDoubleClickSite
    cockpit.interfaces.stageMover.goToSite(siteID)
  File "c:\b24\cockpit\cockpit\interfaces\stageMover.py", line 338, in goToSite
    offsetPosition[i]=offsetPosition[i]+objOffset[i]
TypeError: 'tuple' object does not support item assignm

**Comment by mickp** [comment]
Wrap the assignment in line 337 with a list.
