### ISSUE TITLE
View Last file throws error

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#490]
Clicking on View Last file after a siccesfull z-stack throws this error. The image is shown as normally though...

Traceback (most recent call last):
  File "C:\Users\julio\PycharmProjects\cockpit\cockpit\gui\imageViewer\viewCanvas.py", line 644, in onMouse
    self.updateMouseInfo(self.curMouseX, self.curMouseY)
  File "C:\Users\julio\PycharmProjects\cockpit\cockpit\gui\imageViewer\viewCanvas.py", line 749, in updateMouseInfo
    coords = numpy.array(self.canvasToIndices(x, y), dtype=np.uint)
  File "C:\Users\julio\PycharmProjects\cockpit\cockpit\gui\imageViewer\viewCanvas.py", line 738, in canvasToIndices
    return self.glToIndices(*self.canvasToGl(x, y))
  File "C:\Users\julio\PycharmProjects\cockpit\cockpit\gui\imageViewer\viewCanvas.py", line 723, in canvasToGl
    glx = (-1 + 2 *x / self.w - self.panX * self.zoom) / self.zoom
AttributeError: 'ViewCanvas' object has no attribute 'w'
Traceback (most recent call last):
  File "C:\Users\julio\PycharmProjects\cockpit\cockpit\gui\imageViewer\viewCanvas.py", line 644, in onMouse
    self.updateMouseInfo(self.curMouseX, self.curMouseY)
  File "C:\Users\julio\PycharmProjects\cockpit\cockpit\gui\imageViewer\viewCanvas.py", line 749, in updateMouseInfo
    coords = numpy.array(self.canvasToIndices(x, y), dtype=np.uint)
  File "C:\Users\julio\PycharmProjects\cockpit\cockpit\gui\imageViewer\viewCanvas.py", line 738, in canvasToIndices
    return self.glToIndices(*self.canvasToGl(x, y))
  File "C:\Users\julio\PycharmProjects\cockpit\cockpit\gui\imageViewer\viewCanvas.py", line 723, in canvasToGl
    glx = (-1 + 2 *x / self.w - self.panX * self.zoom) / self.zoom
AttributeError: 'ViewCanvas' object has no attribute 'w'

**Comment by mickp** [comment]
I don't see that exception here.
canvas.w and .h are set by InitGL, which is called the first time the canvas is painted.
The exception is thrown in canvasToGl, which is only called by canvasToIndices, which in turn is currently only used in updateMouseInfo, which is triggered by mouse events. So it looks like the window is processing a mouse event before the canvas has been initialised.
I'll set w and h to None in __init__, and add a condition to the check that's already in updateMouseInfo.
