### ISSUE TITLE
Multisite experiment with no positions marked

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#655]
Clicking the multisite experiment button with no positions marked throws this error:
```python
Traceback (most recent call last):
  File "C:\Users\julio\PycharmProjects\cockpit\cockpit\gui\mainWindow.py", line 135, in <lambda>
    ("Multi-site\nexperiment", lambda evt: multiSiteExperiment.showDialog(self) ),
  File "C:\Users\julio\PycharmProjects\cockpit\cockpit\gui\dialogs\experiment\multiSiteExperiment.py", line 524, in showDialog
    dialog = MultiSiteExperimentDialog(parent)
  File "C:\Users\julio\PycharmProjects\cockpit\cockpit\gui\dialogs\experiment\multiSiteExperiment.py", line 243, in __init__
    buttonSizer.Add(button, 0, wx.ALIGN_RIGHT | wx.ALL, 5)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at ..\..\src\common\sizer.cpp(2098) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
```

**Comment by carandraug** [comment]
This is new with wxPython 4.1.0. Basically, those align right or align left flags are pointless in an horizontal flags. Previously there were asserts in wxWidgets but were being ignored. Since wxPython 4.1.0 debug mode is on by default which causes assertion errors.

Anyway, I fixed this with dc1fc27e922e223bca2 (there were a few other commits doing the same thing all other cockpit).
