### ISSUE TITLE
intensity profile plot problem. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#751]
The intensity profile tool isnt working.

```
Traceback (most recent call last):
  File "c:\b24\cockpit\cockpit\util\intensity.py", line 416, in loadFile
    xpos, ypos = self.profiler.guessBeadCentre()
  File "c:\b24\cockpit\cockpit\util\intensity.py", line 165, in guessBeadCentre
    3*nx / 8 : 5*nx / 8]
TypeError: slice indices must be integers or None or have an __index__ method
Traceback (most recent call last):
  File "c:\b24\cockpit\cockpit\util\intensity.py", line 416, in loadFile
    xpos, ypos = self.profiler.guessBeadCentre()
  File "c:\b24\cockpit\cockpit\util\intensity.py", line 165, in guessBeadCentre
    3*nx / 8 : 5*nx / 8]
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by juliomateoslangerak** [comment]
This is very similar to #558. Incompatibility with python 3 I did some modifications and since then it was working for me.

**Comment by carandraug** [comment]
> This is very similar to #558.

More than very similar, this issue seems to have been fixed as part of that. The line with the issue `3*nx / 8 : 5*nx / 8` has since been changed to return integer.

@iandobbie maybe close as "already fixed"?

**Comment by iandobbie** [comment]
Already fixed. Diamond cryosim is just behind the times.
