### ISSUE TITLE
issue with touchscreen wx.Size call

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#825]
My machine has recently been upgraded to wx 4.2.0 osx-cocoa (phoenix) wxWidgets 3.2.0 and cockpit now bombs on startup with:

Traceback (most recent call last):
  File "/Users/ID/src/cockpit/cockpit/__init__.py", line 193, in OnInit
    module.makeWindow(main_window)
  File "/Users/ID/src/cockpit/cockpit/gui/touchscreen.py", line 1834, in makeWindow
    TouchScreenWindow(parent, title="Touch Screen view")
  File "/Users/ID/src/cockpit/cockpit/gui/touchscreen.py", line 1816, in __init__
    self._do_layout()
  File "/Users/ID/src/cockpit/cockpit/gui/touchscreen.py", line 1826, in _do_layout
    sizer.Add(ImagePreviewPanel(self), 0, wx.EXPAND)
  File "/Users/ID/src/cockpit/cockpit/gui/touchscreen.py", line 1586, in __init__
    self._do_layout()
  File "/Users/ID/src/cockpit/cockpit/gui/touchscreen.py", line 1606, in _do_layout
    self.resetGrid()
  File "/Users/ID/src/cockpit/cockpit/gui/touchscreen.py", line 1670, in resetGrid
    view.change_size(wx.Size(new_width, new_height))
TypeError: Size(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 2 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'int'

I solved this with an int cast in the line calculating new_height

**Comment by iandobbie** [comment]
fixed in master branch with commit 5e23f7f
