### ISSUE TITLE
Issues with fresh install windows python 3.11.1

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#834]
I just tried to install on a new computer and have run into some errors installing. The issue is missing or changed dependencies for wxpython. I know this isn't a cockpit issue but thought I would add a comment about it here. 

System is windows 10 enterprise with python 3.11.1 from python.org and the current master of microscope-cockpit from github. Installed using 
pip install --editable .

First issue is 
```
Collecting wxPython>=4.1
  Downloading wxPython-4.2.0.tar.gz (71.0 MB)
     --------------------------------------- 71.0/71.0 MB 17.2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [8 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\iicadmin\AppData\Local\Temp\pip-install-lz67efyy\wxpython_5b074e9466a24d92b7c44f75e4857f31\setup.py", line 27, in <module>
      from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
    File "C:\Users\iicadmin\AppData\Local\Temp\pip-install-lz67efyy\wxpython_5b074e9466a24d92b7c44f75e4857f31\buildtools\config.py", line 30, in <module>
      from attrdict import AttrDict
  ModuleNotFoundError: No module named 'attrdict'
  [end of output]
```

I then explicitly installed attrdict with pip and reran to get .....

```
Collecting wxPython>=4.1
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [12 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\iicadmin\AppData\Local\Temp\pip-install-hq2bbsin\wxpython_48720378e4514713b8c1614d648f0ba2\setup.py", line 27, in <module>
      from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
    File "C:\Users\iicadmin\AppData\Local\Temp\pip-install-hq2bbsin\wxpython_48720378e4514713b8c1614d648f0ba2\buildtools\config.py", line 30, in <module>
      from attrdict import AttrDict
    File "C:\Users\iicadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\attrdict\__init__.py", line 5, in <module>
      from attrdict.mapping import AttrMap
    File "C:\Users\iicadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\attrdict\mapping.py", line 4, in <module>
      from collections import Mapping
  ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\iicadmin\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py)
  [end of output]
```

Which looks a little more problematic to solve.

**Comment by iandobbie** [comment]
Turns out attrdict is no longer supported and the new interface to collections breaks it with python 3.10 or 3.11. 

A few of the files need 
from collections import XX
changed to 
from collections.abc import XX

**Comment by iandobbie** [comment]
The collections fixes were in attrdict but it seems I should have just installed attrdict3, which solved those problems. 

The build of wxpython then fails because I didn't install vscode package. Once I have this it also doesn't appear to have the requests package, so I needed to "pip install requests". WxPython is still compiling at this moment.

**Comment by iandobbie** [comment]
My build died with the compiler out of heap space. I think I need more than 4GB to build this.

**Comment by iandobbie** [comment]
Killed chrome and left it running and it build eventually, but now I have a very strange error.....
 File "C:\Users\iicadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\wx\core.py", line 12, in <module>
    from ._core import *
ModuleNotFoundError: No module named 'wx._core'

So it isn't able to find the ._core file in the wx dir. The file is there but has no file extension, I think this is a build error on wx, but maybe my compiler isnt properly configured in some way.

**Comment by iandobbie** [comment]
as I suspected this is a build bug in wx. You can add ".cp311-win_amd64.pyd" to a bunch of files in wx but I suggest you stick with python 3.10 for now on windows
