### ISSUE TITLE
Current default install fails as we need a new microscope release. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#835]
If you start with a a clean setup, install python and clone the latest cockpit from master, then install with "pip install .". It grabs the last release of microscope and when you run cockpit it fails with:

Traceback (most recent call last):
  File "c:\users\iicadmin\src\cockpit\cockpit\__init__.py", line 150, in OnInit
    for device in cockpit.depot.initialize(depot_config):
  File "c:\users\iicadmin\src\cockpit\cockpit\depot.py", line 311, in initialize
    for device in deviceDepot.initialize(config):
  File "c:\users\iicadmin\src\cockpit\cockpit\depot.py", line 225, in initialize
    self.initDevice(d)
  File "c:\users\iicadmin\src\cockpit\cockpit\depot.py", line 250, in initDevice
    device.initialize()
  File "c:\users\iicadmin\src\cockpit\cockpit\devices\microscopeDevice.py", line 565, in initialize
    if self._proxy.may_move_on_enable():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iicadmin\AppData\Local\Programs\Python\Python311\Lib\site-packages\Pyro4\core.py", line 280, in __getattr__
    raise AttributeError("remote object '%s' has no exposed attribute or method '%s'" % (self._pyroUri, name))
AttributeError: remote object 'PYRO:obj_d32f53c38a30425ba046a8584086a4ee@localhost:57790' has no exposed attribute or method 'may_move_on_enable'

As the microscope release doesn't have the "may_move_on_enable" functions.

**Comment by iandobbie** [comment]
I should note the solution is to clone the latest master of microscope and install that locally rather than using the release from pipy

**Comment by iandobbie** [comment]
It has been pointed out that if I just go with "pip install cockpit" this would not be an issue. This only fails if you use the development cockpit but not the development microscope. I think this means it is really a non-issue and I will close it
